### ISSUE TITLE
Reset totally the modal when it is closed by the user

### ISSUE THREAD

**Issue by louis-paul** [ProcessOut/processout.js#3]
Not happening right now. For instance, the popup open back to the list of payment gateways.

**Comment by manuel-huez** [comment]
This was actually an intended behaviour, so the customer wouldn't loose the data he had entered in the form (such as shipping address). The form gets reset when refreshing the page. I believe that if the customer clicks on the modal again, he is going to enter the same data anyway. Would like your input on this.

**Comment by louis-paul** [comment]
How about just going back to the main screen then?

**Comment by manuel-huez** [comment]
The modal now resets every time the modal closes.
